### ISSUE TITLE
[提醒]上大开源社区那个门户网站打不开了

### ISSUE THREAD

**Issue by Joe19970619** [shuopensourcecommunity/SHUer.link#2]
https://www.shuosc.org/ 
目前打不开，提醒下你们

**Comment by AdrianDuan** [comment]
你好，接上海市教委通知，为确保进博会期间网络安全，将在2018年11月1号至2018年11月12号关闭校园网的所有外网访问，仅内网可以访问，待进博会结束后。开源社区主页、镜像站等将会恢复访问，感谢您的提醒。
